### PR TITLE
Correct lexer pos

### PR DESCRIPTION
**Pull request by jenshnielsen**
This sits on top of #35 which should be reviewed first. 

Tokens starting with `#` and `@` are cutting of the first element of the token. This means that the lexerpos will be one off when syntax highlighting. This corrects that by updating the lexer position.

### CODE REVIEW

**Comment by jenshnielsen** [comment]
retest this please

**Comment by jenshnielsen** [comment]
retest this please

**Comment by jenshnielsen** [comment]
retest this please

**Comment by jenshnielsen** [comment]
retest this please

**Comment by jenshnielsen** [comment]
retest this please

**Comment by jenshnielsen** [comment]
retest this please

**Comment by jenshnielsen** [comment]
@raquel-ucl and @jamespjh  last change to pyoracc needed for working syntax highlighting in Nammu

**Comment by raquel-ucl** [comment]
Happy to merge. @jamespjh?

**Comment by jamespjh** [comment]
Mergey merge merge.

**Pull request merged**
