### PR TITLE
First attempt at serializing belsunu.atf

### PR DESCRIPTION
**Pull request by raquel-ucl**

### CODE REVIEW

**Comment by raquel-ucl** [comment]
Forgot to push last group of commits! I'll close and make another pull request... 0:)

**Comment by raquel-ucl** [comment]
Last commits pushed now.

**Comment by jenshnielsen** [comment]
retest this please

**Comment by jenshnielsen** [comment]
retest this please

**Comment by jenshnielsen** [comment]
retest this please

**Comment by jenshnielsen** [comment]
retest this please

**Comment by jenshnielsen** [comment]
@raquel-ucl @jamespjh Does any one remember the status of this. It would be nice to get this to a stage where we can unbundle the version of pyoracc bundled in nammmu

**Comment by raquel-ucl** [comment]
I remember it serialises correctly only non composites. I'll have a look and remember where I left it.

**Pull request merged**
